# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To use this:
# gcloud ml-engine versions create vXXX \
# --model <model name> \
# --config config_model_deploy.yaml

description: "demo"
deploymentUri:   gs://ml1-demo-martin/jobs/plane064/1/export/Servo/1508870182
runtimeVersion: '1.10'
machineType: 'mls1-c4-m2' # 4-CPU machines
#autoScaling:
#  minNodes: 10  # minimum number of nodes for autoscaling. The default is 0.